// +build ignore

package main

import (
	"bytes"
	"io"
	"io/ioutil"
	"os"
)

func main() {
	index, err := ioutil.ReadFile("./templates/index.html")
	if err != nil {
		panic(err)
	}

	indexFd, err := os.OpenFile("./templates/index.go", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		panic(err)
	}

	page, err := ioutil.ReadFile("./templates/page.html")
	if err != nil {
		panic(err)
	}

	pageFd, err := os.OpenFile("./templates/page.go", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		panic(err)
	}

	indexBuf := &bytes.Buffer{}
	indexBuf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	indexBuf.WriteString("package templates\n\n")
	indexBuf.WriteString("var Index = []byte(`\n")
	indexBuf.Write(index)
	indexBuf.WriteString("`) // end of indexTemplate\n")

	pageBuf := &bytes.Buffer{}
	pageBuf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	pageBuf.WriteString("package templates\n\n")
	pageBuf.WriteString("var Page = []byte(`\n")
	pageBuf.Write(page)
	pageBuf.WriteString("`) // end of pageTemplate\n")

	io.Copy(indexFd, indexBuf)
	io.Copy(pageFd, pageBuf)
}
