// Code generated by go generate; DO NOT EDIT.

package templates

var Index = []byte(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>kb 101</title>
    <style>
        body {
            font-size: 1.4em;
            font-family: "Courier New", Courier, monospace;
        }
        .body {
            width: 800px;
            max-width: 800px;
            margin: 0 auto;
            padding-top: 1em;
        }
        .heading {
            text-align: center;
            padding-top: 2em;
        }
        pre {
            padding-left: 12px;
            border-left: 2px solid #afafaf;
        }
    </style>
</head>
<body>
<div class="heading"><h1>kb 101</h1></div>
<div class="body">${CONTENT}</div>
</body>
</html>
`) // end of indexTemplate
